"""empty message

Revision ID: 159576f3fcc9
Revises: None
Create Date: 2015-02-23 14:12:47.649000

"""

# revision identifiers, used by Alembic.
revision = '159576f3fcc9'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('hate', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], [u'user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=True),
    sa.Column('articleId', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['articleId'], [u'article.id'], ),
    sa.ForeignKeyConstraint(['userId'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('a')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_comment=u'a',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('comment')
    op.drop_table('article')
    op.drop_table('user')
    ### end Alembic commands ###
